title: Arinze Luke Ozioko
logo: assets/image/profilepix.jpg
description: I'm a skilled data analyst with expertise in SQL, Excel, Python, Tableau, Power BI, and Mathematical Modeling. I'm passionate about decoding complex data, turning raw information into actionable insights. Proficient in SQL queries, advanced analytics with Python, and visualization tools like Tableau and Power BI, I take a holistic approach to extract meaningful conclusions from diverse datasets. Ready to contribute valuable insights and drive data-driven decision-making in dynamic and analytical environments.
show_download: 
theme: jekyll-theme-minimal
