title: Arinze Luke Ozioko
logo: assets/image/profilepix.jpg
description: I'm a skilled data analyst with expertise in SQL, Excel, Python, Tableau, Power BI, and Mathematical Modeling. 
show_download: 
theme: jekyll-theme-minimal
